### ISSUE TITLE
I submitted a data use application. However, it has not been approved.

### ISSUE THREAD

**Issue by RongqinChen** [nrodemund/sicdb#1]
Dear database manager,

I submitted a data use application on the physionet website long time ago. However, the application has not been approved and no reasons were given. Could you tell me why my application is still pending and the requirement for the data use application? Below is my application.

"""
Title: Early Prediction of Critical Events in the ICU Using Machine Learning

We are a team from [Shenzhen Institute of Advanced Technology](https://www.siat.ac.cn/) (SIAT). We are committed to addressing key technologies for the monitoring and early warning of critical and acute illnesses. 

We would like to use this dataset for a research which aims to develop a machine learning model for the early prediction of critical events in the ICU. By leveraging patient data, such as vital signs, laboratory results, and electronic health records, the model could assist clinicians in identifying patients at risk of deterioration and facilitate timely interventions to improve patient outcomes and reduce hospital resource utilization. 

Critical events in the ICU, such as septic shock, acute respiratory distress syndrome (ARDS), and acute kidney injury (AKI), are associated with high morbidity and mortality rates. Early identification of these events is crucial for the timely initiation of appropriate interventions. Machine learning techniques have shown promise in predicting and identifying critical events, but their application in the ICU setting remains limited. This project aims to develop models that can accurately predict critical events in the ICU and facilitate timely interventions.

Objectives of this project include:

1. To develop a machine learning model that can accurately predict critical events in ICU patients, using patient data such as vital signs, laboratory results, and electronic health records.
2. To evaluate the performance of the model in terms of sensitivity, specificity, positive predictive value, and negative predictive value.
3. To compare the performance of the developed model with existing prediction scores and tools.
4. To assess the clinical utility of the model in terms of its potential to improve patient outcomes and reduce hospital resource utilization.

Expected outcomes and significance of this project include:

The successful development of a machine learning-based model for early prediction of critical events in the ICU has the potential to improve patient outcomes through timely interventions and more efficient allocation of hospital resources. This research project may pave the way for further exploration of machine learning applications in the ICU setting and contribute to the growing body of literature on AI in healthcare.
”“”

I am looking forward to your reply.

Sincerely.
Rongqin Chen

**Comment by nrodemund** [comment]
Dear Rongqin Chen!
I have approved your request. If you need any help feel free to ask!
best regards, Niklas

**Comment by RongqinChen** [comment]
Thank you very much!

**Comment by njtp111** [comment]
@nrodemund 
Dear database manager,

I also submitted the application, could you help me approve it?  Thank you very much.
best regards, Jiacong Mi

Below is my application.

"""
Title：Medication recommendation based on electronic health records

I am writing on behalf of the research team from Southeast University, specializing in electronic health record-based medication recommendations. Our recent research, accessible at https://arxiv.org/abs/2307.03332, showcased our expertise in this field using the MIMIC dataset.

We are interested in expanding our research to include the "Salzburg Intensive Care database (SICdb)". Given our track record of responsible data handling and contribution to the field, we kindly request access to the SICdb to further our medication recommendation research.

Thank you for considering our request. We are eager to contribute to the advancement of intensive care research through the SICdb.
”“”
